import React from "react";
import "./globals.css";

import { Nunito } from "next/font/google";
import { Metadata } from "next";
import { Header } from "@/components/shared";

const nunito = Nunito({
  subsets: ["cyrillic"],
  variable: "--font-nunito",
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Time to work",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={nunito.variable} lang="ru">
      <head>
        <link data-rh="true" rel="icon" href="/logo.png" />
      </head>

      <body>
        <Header />
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
